apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wynnsource-dev
resources:
- postgres.yaml
- redis.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- migration-job.yaml
images:
- name: ghcr.io/wynnsource/wynnsource-server
  newName: ghcr.io/wynnsource/wynnsource-server
  newTag: 76ff09226de596174e79eb58ab9bbd2a82f7a6c6
