apiVersion: batch/v1
kind: Job
metadata:
  name: wynnsource-migration
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    argocd.argoproj.io/sync-wave: "1"
spec:
  backoffLimit: 3
  template:
    spec:
      containers:
        - name: migration
          image: ghcr.io/wynnsource/wynnsource-server:latest
          command: ["uv", "run", "alembic", "upgrade", "head"]
          envFrom:
            - secretRef:
                name: wynnsource-secrets
          env:
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: wynnsource-pg-app
                  key: host
            - name: POSTGRES_PORT
              valueFrom:
                secretKeyRef:
                  name: wynnsource-pg-app
                  key: port
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: wynnsource-pg-app
                  key: user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wynnsource-pg-app
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: wynnsource-pg-app
                  key: dbname
      restartPolicy: OnFailure
