apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: wynnsource-pg
spec:
  instances: 1
  storage:
    size: 5Gi
  postgresql:
    parameters:
      max_connections: "100"
  bootstrap:
    initdb:
      database: wcs_db
      owner: wynnsource
