apiVersion: redis.redis.opstreelabs.in/v1beta2
kind: Redis
metadata:
  name: wynnsource-redis
spec:
  kubernetesConfig:
    image: redis:7-alpine
    resources:
      requests: { cpu: 50m, memory: 64Mi }
      limits: { cpu: 200m, memory: 128Mi }
  storage:
    volumeClaimTemplate:
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
