apiVersion: v1
kind: Service
metadata:
  name: wynnsource-server
  labels:
    app: wynnsource-server
spec:
  type: ClusterIP
  selector:
    app: wynnsource-server
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
